// <auto-generated />
using System;
using Attendance.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Attendance.Persistance.Migrations
{
    [DbContext(typeof(AttendanceContext))]
    [Migration("20190106183928_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Attendance.Domain.Presence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<Guid?>("SessionEnrolledId");

                    b.Property<Guid>("StudentId");

                    b.Property<DateTime>("SubmitDate");

                    b.HasKey("Id");

                    b.HasIndex("SessionEnrolledId");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("Attendance.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Available");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired();

                    b.Property<DateTime>("EndTime");

                    b.Property<Guid>("LaboratoryId");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Attendance.Domain.Presence", b =>
                {
                    b.HasOne("Attendance.Domain.Session", "SessionEnrolled")
                        .WithMany("Presences")
                        .HasForeignKey("SessionEnrolledId");
                });
#pragma warning restore 612, 618
        }
    }
}
